# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ombutqmgx8psvQT-97pobUmAfCuc7kPN
"""



import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Solar Power Generation Dashboard",
    page_icon="☀️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS FOR BETTER UI ---
st.markdown("""
    <style>
    .main-title {
        font-size: 38px;
        font-weight: bold;
        color: #FF4B4B;
        text-align: center;
        margin-bottom: 20px;
    }
    .metric-box {
        background-color: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        text-align: center;
        margin: 10px 0;
    }
    </style>
""", unsafe_allow_html=True)  # <-- Fixed parameter here

# --- HELPER DATA GENERATOR / PIPELINE ---
@st.cache_data
def load_and_preprocess_data(file):
    try:
        df = pd.read_csv(file)
    except Exception:
        # Fallback dummy dataframe matching user schema if no file uploaded
        columns = [
            'distance_to_solar_noon', 'temperature', 'wind_direction',
            'wind_speed', 'sky_cover', 'visibility', 'humidity',
            'average_wind_speed', 'average_pressure', 'power_generated'
        ]
        np.random.seed(42)
        dummy_data = np.random.rand(100, 10)
        df = pd.DataFrame(dummy_data, columns=columns)
        # Scale target to realistic lookalikes
        df['power_generated'] = df['power_generated'] * 5000

    # Missing value treatment
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].fillna(df[col].mode()[0])
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col])
        else:
            df[col] = df[col].fillna(df[col].mean())

    return df

# --- SIDEBAR CONTENT ---
st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3222/3222672.png", width=100)
st.sidebar.title("Navigation & Settings")
app_mode = st.sidebar.radio("Go to Page:", ["Project Overview", "Data Explorer & EDA", "Model Evaluation", "Live Prediction"])

st.sidebar.markdown("---")
uploaded_file = st.sidebar.file_uploader("Upload your 'solarpowergeneration.csv'", type=["csv"])

# Initialize data
data = load_and_preprocess_data(uploaded_file)

# --- MAIN APP LOGIC ---

if app_mode == "Project Overview":
    st.markdown('<div class="main-title">☀️ Solar Power Generation Forecasting</div>', unsafe_allow_html=True)

    st.markdown("""
    ### 🎯 Objective
    This is a **Regression Project** aiming to accurately model and predict solar energy production (`power_generated` in Joules every 3 hours) as a function of real-time environmental attributes.

    ### 📋 Dataset Features Breakdown
    """)

    cols = st.columns(2)
    with cols[0]:
        st.markdown("""
        * **Distance to Solar Noon:** In radians.
        * **Temperature:** Daily average temperature (°C).
        * **Wind Direction:** Daily average wind direction (0°-360°).
        * **Wind Speed & Average Wind Speed:** Measured in meters per second.
        * **Sky Cover:** Five-step scale (0 = Clear, 4 = Fully Covered).
        """)
    with cols[1]:
        st.markdown("""
        * **Visibility:** Measured in kilometers.
        * **Humidity:** Relative humidity percentage (%).
        * **Average Pressure:** Barometric pressure (inches of mercury).
        * **Power Generated (Target variable):** Joules produced per 3 hours.
        """)

    st.markdown("---")
    st.subheader("📅 Project Roadmap & Milestones")
    timeline_df = pd.DataFrame({
        "Task/Phase": ["Kick off & Objective", "Data Details & Setup", "EDA & Cleaning", "Model Building & Eval", "Deployment", "Final Presentation"],
        "Duration": ["Day 1", "2-3 Days", "1 Week", "1 Week", "1 Week", "1 Week"],
        "Start - End Date": ["08-Aug-2025", "09-Aug-2025", "14-Aug-2025", "22-Aug-2025", "29-Aug-2025", "05-Sep-2025"]
    })
    st.table(timeline_df)


elif app_mode == "Data Explorer & EDA":
    st.subheader("📊 Exploratory Data Analysis & Cleaned Dataset")

    if uploaded_file is None:
        st.info("💡 Showing structural placeholder preview. Please upload your actual CSV via the sidebar to see live statistics!")

    st.dataframe(data.head(10), use_container_width=True)

    # Simple Metrics Row
    m1, m2, m3 = st.columns(3)
    m1.metric("Total Row Count", data.shape[0])
    m2.metric("Total Column Features", data.shape[1] - 1)
    m3.metric("Target Feature", "power_generated")

    st.markdown("---")

    tab1, tab2 = st.tabs(["📉 Correlation Heatmap", "📦 Feature Distributions"])

    with tab1:
        st.write("##### Feature Correlation Analysis Matrix")
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt=".2f", ax=ax)
        st.pyplot(fig)

    with tab2:
        st.write("##### Numerical Distributions & Outliers")
        selected_col = st.selectbox("Select variable to view Boxplot & Distribution:", data.columns[:-1])
        fig, ax = plt.subplots(1, 2, figsize=(12, 4))
        sns.histplot(data[selected_col], kde=True, ax=ax[0], color='orange')
        sns.boxplot(y=data[selected_col], ax=ax[1], color='coral')
        st.pyplot(fig)


elif app_mode == "Model Evaluation":
    st.subheader("🤖 Model Benchmarking & Performance Summary")

    # Split independent / dependent
    if 'power_generated' in data.columns:
        X = data.drop(columns=['power_generated'])
        y = data['power_generated']
    else:
        y = data.iloc[:, -1]
        X = data.iloc[:, :-1]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # User choice selector
    model_choice = st.selectbox("Choose a Trained Regressor Algorithm to Evaluate:",
                                ["Linear Regression", "Decision Tree", "Random Forest", "KNN", "Support Vector Machine (SVM)"])

    # Fit selected model
    if model_choice == "Linear Regression":
        model = LinearRegression()
    elif model_choice == "Decision Tree":
        model = DecisionTreeRegressor(random_state=42)
    elif model_choice == "Random Forest":
        model = RandomForestRegressor(n_estimators=100, random_state=42)
    elif model_choice == "KNN":
        model = KNeighborsRegressor(n_neighbors=5)
    elif model_choice == "Support Vector Machine (SVM)":
        model = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=0.1)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Evaluation Metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("MAE", f"{mae:.2f}")
    c2.metric("MSE", f"{mse:.2f}")
    c3.metric("RMSE", f"{rmse:.2f}")
    c4.metric("R² Score", f"{r2:.4f}")

    # Plot Actual vs Predicted
    st.markdown("---")
    st.write(f"##### {model_choice}: Actual vs. Predicted Target Response Scatter")
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.scatter(y_test, y_pred, alpha=0.6, color='dodgerblue', edgecolors='k')
    ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
    ax.set_xlabel("Actual Power Generated")
    ax.set_ylabel("Predicted Power Generated")
    ax.set_title(f"{model_choice} Fit")
    st.pyplot(fig)


elif app_mode == "Live Prediction":
    st.subheader("🔮 Live Solar Inference Simulator")
    st.write("Tune environmental telemetry metrics using the panels below to predict instantaneous electricity generation.")

    # Form layout for user inputs
    with st.form("inference_form"):
        col1, col2, col3 = st.columns(3)

        with col1:
            dist_noon = col1.number_input("Distance to Solar Noon (rad)", min_value=0.0, max_value=3.15, value=0.5, step=0.05)
            temp = col1.number_input("Temperature (°C)", min_value=-10.0, max_value=50.0, value=25.0, step=0.5)
            wind_dir = col1.number_input("Wind Direction (0-360°)", min_value=0.0, max_value=360.0, value=180.0, step=1.0)

        with col2:
            wind_spd = col2.number_input("Wind Speed (m/s)", min_value=0.0, max_value=50.0, value=4.5, step=0.1)
            sky_cov = col2.slider("Sky Cover Rating (0-4)", min_value=0, max_value=4, value=1)
            visib = col2.number_input("Visibility (km)", min_value=0.0, max_value=50.0, value=10.0, step=0.5)

        with col3:
            humidity = col3.number_input("Humidity (%)", min_value=0.0, max_value=100.0, value=60.0, step=1.0)
            avg_wind = col3.number_input("3hr Average Wind Speed (m/s)", min_value=0.0, max_value=50.0, value=4.2, step=0.1)
            avg_press = col3.number_input("3hr Average Pressure (inHg)", min_value=25.0, max_value=35.0, value=29.92, step=0.05)

        submit_btn = st.form_submit_button("⚡ Calculate Generated Power")

    if submit_btn:
        if 'power_generated' in data.columns:
            X = data.drop(columns=['power_generated'])
            y = data['power_generated']
        else:
            y = data.iloc[:, -1]
            X = data.iloc[:, :-1]

        prod_model = RandomForestRegressor(n_estimators=100, random_state=42)
        prod_model.fit(X, y)

        # Format the user features vector to exactly match training shape
        input_vector = np.array([[dist_noon, temp, wind_dir, wind_spd, sky_cov, visib, humidity, avg_wind, avg_press]])
        prediction = prod_model.predict(input_vector)[0]

        st.success("🎉 Prediction calculation finished!")
        st.markdown(f"""
        <div class="metric-box">
            <h3>Predicted Power Output</h3>
            <h1 style="color:#FF4B4B;">{prediction:,.2f} Joules</h1>
            <small>Estimated for a continuous 3-Hour Period</small>
        </div>
        """, unsafe_allow_html=True)
